### ISSUE TITLE
how to make the eyes close to each other?

### ISSUE THREAD

**Issue by a-ssassi-n** [jfmdev/jqEye#1]
I want to bring the two circular eyes close to each other. how to do it? please expalin.
Thanks in advance

**Comment by jfmdev** [comment]
I assume that you are talking about the "Advanced demo", since you do not indicate any further details.
You can move the eyes by modifying the HTML elements or the CSS code linked to the "div" elements that holds the eyes.
For example, in http://jsfiddle.net/78ktpaqv/6/ I modified the CSS code in order to change "width" of "div.eyes" from "160px" to "120px", making the eyes to be closer.

**Comment by a-ssassi-n** [comment]
Thankyou For your reply. I had already got it done
